dataset_dir: data/training/dex-net_2.1/dexnet_2.1_eps_50
split_name: image_wise
image_field_name: depth_ims_tf_table
pose_field_name: hand_poses
target_metric_name: grasp_metrics
metric_thresh: 0.002
gripper_mode: legacy_parallel_jaw